### ISSUE TITLE
make docker-machine-driver-xhyve go gettable

### ISSUE THREAD

**Issue by saljam** [zchee/docker-machine-driver-xhyve#49] opened 2016-01-08 20:47 UTC
Building with the makefile might be useful for development, but you don't always need one for Go and being able to install the driver binary by just running:

    go get github.com/zchee/docker-machine-driver-xhyve

makes it easier to get started and is more idiomatic Go.

**Comment by saljam** [comment] 2016-01-08 20:52
I propose we do that by moving the go files in the root directory into a directory of their own called "xhyve" (to match the package name) and moving bin/main.go to the root. (Or to cmd/docker-machine-driver-xhyve similar to how [golang.org/x/tools](https://github.com/golang/tools/) does it for example.)

What do you think?

**Comment by zchee** [comment] 2016-01-08 22:42
@saljam Thanks issue!

I was inspired by your comments(It's not that the folder structure), I have testing it now.
I will reply later.

**Comment by zchee** [comment] 2016-01-09 02:40
@saljam I think so, too.
The reason is that the first `docker-machine` driver sample repository was that folder structure.
As you have proposed, I think,

- Move `zchee/docker-machine-driver-xhyve/bin/main.go` to `zchee/docker-machine-driver-xhyve/main.go`
- Move `zchee/docker-machine-driver-xhyve/*.go` to `zchee/docker-machine-driver-xhyve/xhyve`
- Change `main.go` import pkg to `zchee/docker-machine-driver-xhyve/xhyve`

Same as https://github.com/saljam/docker-machine-driver-xhyve/commit/9967bae0cd7a796bdcd528b898b6bff1ac981be3.

However, in a typical docker-machine driver will be complete in it, but `docker-machine-driver-xhyve` binary need owner to `root:wheel`, and set root uid (`-rwsr-xr-x root:wheel`) hack.
The caused by `vmnet.framework` required `sudo`.
See https://github.com/zchee/docker-machine-driver-xhyve/blob/master/Makefile#L119

So, Folder structure will be clean, but can not full installation only `go get` for now.

**Comment by saljam** [comment] 2016-01-09 09:12
Thanks! And yes, of course, it will still need to be run as root.

**Comment by zchee** [comment] 2016-01-12 13:33
Merged https://github.com/zchee/docker-machine-driver-xhyve/pull/53

Close.

**Closed by zchee** 2016-01-12 13:33 UTC
