### ISSUE TITLE
Show a nice warning when running without root

### ISSUE THREAD

**Issue by johanneswuerbach** [zchee/docker-machine-driver-xhyve#64] opened 2016-01-13 11:56 UTC
Currently users running `docker-machine create -d xhyve test` without root are receiving an ugly error message `Error creating machine: Error in driver during machine creation: exit status 1`

Instead this driver should print a nice warning and tell the users that root is required.

**Comment by zchee** [comment] 2016-01-13 12:15
@johanneswuerbach Yes, I think so, too.

I tried `os.Chown(os.Arg[0], 0, 0)` on `PreCreateCheck()`, but does not work.
Maybe caused by first run command user to has not `root` permission.

I think, the `uid` check insert to `PreCreateCheck()`

e.g. (example code. too dirty.)
```go
// Print driver version, Check VirtualBox version
func (d *Driver) PreCreateCheck() error {
	.
	.
	.
	bin, err := os.Stat(os.Args[0])
	if err != nil {
		return err
	}
	if int(bin.Sys().(*syscall.Stat_t).Uid) == 501 {
		log.Infof("docker-machine-driver-xhyve need root owner. See https://github.com/zchee/docker-machine-driver-xhyve#install")
		os.Exit(1)
	}

	return nil
}
```

What do you think?

**Comment by johanneswuerbach** [comment] 2016-01-13 12:51
Yep, exactly like this :+1:

**Comment by zchee** [comment] 2016-01-13 12:56
@johanneswuerbach :)
If has been merged PR on homebrew, I will add this method.
and, Bump version v0.2.2 to later.

**Comment by zchee** [comment] 2016-01-20 09:38
@johanneswuerbach I created a pull-request :)
https://github.com/zchee/docker-machine-driver-xhyve/pull/75

**Comment by zchee** [comment] 2016-01-22 01:50
Merged https://github.com/zchee/docker-machine-driver-xhyve/commit/278eb5a18af59264ddc5dd0492f78d853beae293.

If you find a bug, Could you tell me?
and, I will increase the more test for the future.

Close.

**Closed by zchee** 2016-01-22 01:50 UTC
Labels: in progress

**Comment by korsmakolnikov** [comment] 2016-05-21 11:31
this is really annoying. I still have this issue on mac os 10.11.4
